spring:
  application:
    name: qiqi-metric
  jackson:
    date-format: yyyyMMddHHMMss
    time-zone: GMT+8
  boot:
    admin:
      ui:
        title: qiqi-gateway服务监控中心


server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

logging:
  level:
    root: info
  file:
    path: /home/logs/${spring.application.name}

