# spring配置
spring:
  application:
    name: qiqi-metric
  jackson:
    date-format: yyyyMMddHHMMss
    time-zone: GMT+8
  boot:
    admin:
      ui:
        title: qiqi-gateway服务监控中心
        external-views:
          - label: "注销"
            url: /logout
            order: 2000
  # 制定配置文件，配合logback配置中的springProfile标签
  profiles:
    active: dev
  # spring-boot-admin配置日志颜色
  output:
    ansi:
      enabled: ALWAYS


# server配置
server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8


# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


# actuator监控
management:
  endpoints:
    enabled-by-default: true
    web:
      # health和info可见, gateway允许动态增加路由
      # 包括所有端点
      exposure:
        include: "*"
        # 排除端点
        exclude: shutdown,restart,refresh,caches
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
    logfile:
      external-file: ${logging.file.path}/console.log

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: C:\home/logs/${spring.application.name}


qiqi-gateway:
  sa-token:
    includeList:
      - /**
    excludeList:
      - /assets/**
      - /actuator/**
      - /instances/**
      - /favicon.ico
      - /login
    origin-url-session: origin-url
    login:
      index-url: /
      login-url: /login
      method: POST
      username-field: username
      password-field: password
      username: admin
      password: admin
      login-id: 1


