# 应用名称
spring:
  application:
    name: qiqi-eureka-server
  profiles:
    active: dev


# eureka服务端口
server:
  port: 8761


# actuator监控
management:
  endpoints:
    enabled-by-default: true
    web:
      # health和info可见, gateway允许动态增加路由
      # 包括所有端点
      exposure:
        include: "*"
        # 排除端点
        exclude: shutdown
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml