# 应用名称
spring:
  application:
    name: qiqi-eureka-server
  # 制定配置文件，配合logback配置中的springProfile标签
  profiles:
    active: dev
  # spring-boot-admin配置日志颜色
  output:
    ansi:
      enabled: ALWAYS

# eureka服务端口
server:
  port: 8761


# actuator监控
management:
  endpoints:
    enabled-by-default: true
    web:
      # health和info可见, gateway允许动态增加路由
      # 包括所有端点
      exposure:
        include: "*"
        # 排除端点
        exclude: shutdown
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
    logfile:
      external-file: ${logging.file.path}/console.log

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: C:\home/logs/${spring.application.name}