# 应用名称
spring:
  application:
    name: qiqi-eureka-server

# eureka服务端口
server:
  port: 8761

# eureka配置信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
